"""add webhook fields

Revision ID: 0f329d31d126
Revises: 87ecc247d67e
Create Date: 2026-09-02 23:51:17.346994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f329d31d126'
down_revision: Union[str, None] = '87ecc247d67e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('settl_event_type', sa.String(), nullable=True),
    sa.Column('merchant_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('settl_event_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_event_id', name='uq_provider_external_event_id')
    )
    op.create_index(op.f('ix_webhook_events_account_id'), 'webhook_events', ['account_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_external_event_id'), 'webhook_events', ['external_event_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_merchant_id'), 'webhook_events', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_provider'), 'webhook_events', ['provider'], unique=False)
    op.create_index(op.f('ix_webhook_events_settl_event_id'), 'webhook_events', ['settl_event_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_settl_event_type'), 'webhook_events', ['settl_event_type'], unique=False)
    op.create_index(op.f('ix_webhook_events_status'), 'webhook_events', ['status'], unique=False)
    op.add_column('revenue_events', sa.Column('payment_id', sa.String(), nullable=True))
    op.add_column('revenue_events', sa.Column('payment_link_id', sa.String(), nullable=True))
    op.add_column('revenue_events', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('revenue_events', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('revenue_events', sa.Column('webhook_event_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_revenue_events_payment_id'), 'revenue_events', ['payment_id'], unique=False)
    op.create_index(op.f('ix_revenue_events_payment_link_id'), 'revenue_events', ['payment_link_id'], unique=False)
    op.create_index(op.f('ix_revenue_events_webhook_event_id'), 'revenue_events', ['webhook_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revenue_events_webhook_event_id'), table_name='revenue_events')
    op.drop_index(op.f('ix_revenue_events_payment_link_id'), table_name='revenue_events')
    op.drop_index(op.f('ix_revenue_events_payment_id'), table_name='revenue_events')
    op.drop_column('revenue_events', 'webhook_event_id')
    op.drop_column('revenue_events', 'payment_status')
    op.drop_column('revenue_events', 'payment_method')
    op.drop_column('revenue_events', 'payment_link_id')
    op.drop_column('revenue_events', 'payment_id')
    op.drop_index(op.f('ix_webhook_events_status'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_settl_event_type'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_settl_event_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_provider'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_merchant_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_external_event_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_account_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
