"""Add subscription fields

Revision ID: 12b87af7dc51
Revises: 379cb1d9c74a
Create Date: 2026-09-02 15:15:22.606204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b87af7dc51'
down_revision: Union[str, None] = '379cb1d9c74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('subscription_id', sa.String(), nullable=True))
    op.add_column('recovery_cases', sa.Column('billing_cycle_id', sa.String(), nullable=True))
    op.add_column('recovery_cases', sa.Column('provider_state', sa.String(), nullable=True))
    op.create_index(op.f('ix_recovery_cases_billing_cycle_id'), 'recovery_cases', ['billing_cycle_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_subscription_id'), 'recovery_cases', ['subscription_id'], unique=False)
    op.add_column('revenue_events', sa.Column('subscription_id', sa.String(), nullable=True))
    op.add_column('revenue_events', sa.Column('billing_cycle_id', sa.String(), nullable=True))
    op.add_column('revenue_events', sa.Column('provider_state', sa.String(), nullable=True))
    op.create_index(op.f('ix_revenue_events_billing_cycle_id'), 'revenue_events', ['billing_cycle_id'], unique=False)
    op.create_index(op.f('ix_revenue_events_subscription_id'), 'revenue_events', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revenue_events_subscription_id'), table_name='revenue_events')
    op.drop_index(op.f('ix_revenue_events_billing_cycle_id'), table_name='revenue_events')
    op.drop_column('revenue_events', 'provider_state')
    op.drop_column('revenue_events', 'billing_cycle_id')
    op.drop_column('revenue_events', 'subscription_id')
    op.drop_index(op.f('ix_recovery_cases_subscription_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_billing_cycle_id'), table_name='recovery_cases')
    op.drop_column('recovery_cases', 'provider_state')
    op.drop_column('recovery_cases', 'billing_cycle_id')
    op.drop_column('recovery_cases', 'subscription_id')
    # ### end Alembic commands ###
