"""Add Invoice model

Revision ID: 2aff036f0996
Revises: 12b87af7dc51
Create Date: 2026-09-02 19:54:53.893236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aff036f0996'
down_revision: Union[str, None] = '12b87af7dc51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('external_invoice_id', sa.String(), nullable=True),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('paid_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_external_invoice_id'), 'invoices', ['external_invoice_id'], unique=False)
    op.create_index(op.f('ix_invoices_merchant_id'), 'invoices', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.add_column('recovery_cases', sa.Column('invoice_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_recovery_cases_invoice_id'), 'recovery_cases', ['invoice_id'], unique=False)
    op.create_foreign_key(None, 'recovery_cases', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.add_column('revenue_events', sa.Column('invoice_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_revenue_events_invoice_id'), 'revenue_events', ['invoice_id'], unique=False)
    op.create_foreign_key(None, 'revenue_events', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'revenue_events', type_='foreignkey')
    op.drop_index(op.f('ix_revenue_events_invoice_id'), table_name='revenue_events')
    op.drop_column('revenue_events', 'invoice_id')
    op.drop_constraint(None, 'recovery_cases', type_='foreignkey')
    op.drop_index(op.f('ix_recovery_cases_invoice_id'), table_name='recovery_cases')
    op.drop_column('recovery_cases', 'invoice_id')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_merchant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_external_invoice_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
