"""Update Notification model

Revision ID: 342bd6bb5f2f
Revises: d644801bc4cf
Create Date: 2026-09-02 13:28:34.137381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342bd6bb5f2f'
down_revision: Union[str, None] = 'd644801bc4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('message_type', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('provider_reference', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('failure_reason', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'sent_at')
    op.drop_column('notifications', 'failure_reason')
    op.drop_column('notifications', 'provider_reference')
    op.drop_column('notifications', 'message_type')
    op.drop_column('notifications', 'provider')
    # ### end Alembic commands ###
