"""Add CheckoutSession

Revision ID: 379cb1d9c74a
Revises: 342bd6bb5f2f
Create Date: 2026-09-02 14:40:48.184434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '379cb1d9c74a'
down_revision: Union[str, None] = '342bd6bb5f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkout_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('payment_attempted_at', sa.DateTime(), nullable=True),
    sa.Column('payment_succeeded_at', sa.DateTime(), nullable=True),
    sa.Column('abandonment_deadline', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkout_sessions_merchant_id'), 'checkout_sessions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_order_id'), 'checkout_sessions', ['order_id'], unique=False)
    op.create_index('ix_checkout_sessions_status_deadline', 'checkout_sessions', ['status', 'abandonment_deadline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_checkout_sessions_status_deadline', table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_order_id'), table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_merchant_id'), table_name='checkout_sessions')
    op.drop_table('checkout_sessions')
    # ### end Alembic commands ###
