"""Add merchant_id to EvaluationRun

Revision ID: 508a6d4ddb93
Revises: 0f329d31d126
Create Date: 2026-09-04 23:53:19.072321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '508a6d4ddb93'
down_revision: Union[str, None] = '0f329d31d126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluation_runs', sa.Column('merchant_id', sa.String(), server_default='MER_DEMO_01', nullable=False))
    op.create_index(op.f('ix_evaluation_runs_merchant_id'), 'evaluation_runs', ['merchant_id'], unique=False)
    op.alter_column('evaluation_traces', 'ground_truth_recoverable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('evaluation_traces', 'ground_truth_ideal_action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('evaluation_traces', 'ground_truth_scenario',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('evaluation_traces', 'is_decision_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('evaluation_traces', 'is_escalation_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evaluation_traces', 'is_escalation_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('evaluation_traces', 'is_decision_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('evaluation_traces', 'ground_truth_scenario',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('evaluation_traces', 'ground_truth_ideal_action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('evaluation_traces', 'ground_truth_recoverable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_evaluation_runs_merchant_id'), table_name='evaluation_runs')
    op.drop_column('evaluation_runs', 'merchant_id')
    # ### end Alembic commands ###
