"""Add Case 5 fields to Promise model

Revision ID: 87ecc247d67e
Revises: 2aff036f0996
Create Date: 2026-09-02 22:05:09.088859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87ecc247d67e'
down_revision: Union[str, None] = '2aff036f0996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promises', sa.Column('merchant_id', sa.String(), nullable=False))
    op.add_column('promises', sa.Column('invoice_id', sa.String(), nullable=True))
    op.add_column('promises', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('promises', sa.Column('fulfilled_amount_paise', sa.Integer(), nullable=False))
    op.add_column('promises', sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('promises', sa.Column('broken_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('promises', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_promises_invoice_id'), 'promises', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_promises_merchant_id'), 'promises', ['merchant_id'], unique=False)
    op.create_foreign_key(None, 'promises', 'merchants', ['merchant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'promises', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.drop_column('promises', 'verified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promises', sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'promises', type_='foreignkey')
    op.drop_constraint(None, 'promises', type_='foreignkey')
    op.drop_index(op.f('ix_promises_merchant_id'), table_name='promises')
    op.drop_index(op.f('ix_promises_invoice_id'), table_name='promises')
    op.drop_column('promises', 'updated_at')
    op.drop_column('promises', 'broken_at')
    op.drop_column('promises', 'fulfilled_at')
    op.drop_column('promises', 'fulfilled_amount_paise')
    op.drop_column('promises', 'created_by')
    op.drop_column('promises', 'invoice_id')
    op.drop_column('promises', 'merchant_id')
    # ### end Alembic commands ###
