"""Add Promise model

Revision ID: d644801bc4cf
Revises: 0001_initial_schema
Create Date: 2026-09-01 23:47:10.254081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd644801bc4cf'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promises',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('promised_amount_paise', sa.Integer(), nullable=False),
    sa.Column('promise_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promises_case_id'), 'promises', ['case_id'], unique=False)
    op.create_index(op.f('ix_promises_customer_id'), 'promises', ['customer_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_name'), 'audit_logs', ['event_name'], unique=False)
    op.create_index(op.f('ix_notifications_case_id'), 'notifications', ['case_id'], unique=False)
    op.drop_constraint('policies_merchant_id_key', 'policies', type_='unique')
    op.drop_constraint('recovery_actions_reference_id_key', 'recovery_actions', type_='unique')
    op.create_index(op.f('ix_recovery_actions_reference_id'), 'recovery_actions', ['reference_id'], unique=True)
    op.create_index(op.f('ix_webhook_events_event_type'), 'webhook_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_event_type'), table_name='webhook_events')
    op.drop_index(op.f('ix_recovery_actions_reference_id'), table_name='recovery_actions')
    op.create_unique_constraint('recovery_actions_reference_id_key', 'recovery_actions', ['reference_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('policies_merchant_id_key', 'policies', ['merchant_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_notifications_case_id'), table_name='notifications')
    op.drop_index(op.f('ix_audit_logs_event_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_promises_customer_id'), table_name='promises')
    op.drop_index(op.f('ix_promises_case_id'), table_name='promises')
    op.drop_table('promises')
    # ### end Alembic commands ###
